# Generated by Django 5.2 on 2025-06-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company_website',
            field=models.CharField(),
        ),
    ]
