# Generated by Django 5.2 on 2025-06-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_name_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cv_url',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
